### ISSUE TITLE
Facets - distinguish "more" from regular items

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/katalog#26]
Now, regular items seem identical to "more" controls. We need to distinguish them somehow... Bold? Color?
![image](https://github.com/datagov-cz/nkod-registrovane-aplikace/assets/718827/18d88adc-54b0-480e-9624-e2a93fd562ed)

**Comment by skodapetr** [comment]
@jakubklimek Italic?

![image](https://github.com/user-attachments/assets/ac175ace-9d39-4d84-bece-236f37e97c65)

**Comment by jakubklimek** [comment]
Yes.

 
Could we also maybe do a doubleline or something like that?  Now it seems slike just another row in the table...
